server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Ramis-Bilalov/spring-cloud-config/blob/main.git
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    baseline-on-migrate: true